name: "TextNow Autosend"
on:
  #push: # 触发机制为push操作
  #  branches: main
  workflow_dispatch: # 手动触发
  schedule: # 触发机制为定时任务
    - cron: "15 5 * * 1,3,5" # 13点15分自动执行（默认UTC时区）
jobs:
  autosend:
    runs-on: ubuntu-latest # 运行环境为最新的Ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # 使用官方提供的checkout 2.0版本获取代码
      - name: Setup node.js
        uses: actions/setup-node@v1 # 使用官方提供的setup-node 1.0版本配置node环境
        with:
          node-version: "14.x"
      - name: Cache cookies
        uses: actions/cache@v2
        with:
          path: ~/cache.tgz
          key: ${{ secrets.CACHE_NAME }}-${{ github.run_id }} # CACHE_NAME 缓存名字，防止泄漏，自行设置
          restore-keys: ${{ secrets.CACHE_NAME }}-
      - name: Install dependencies
        run: npm install
      - name: Run autosend
        env:
          TEXTNOW_COOKIES: ${{secrets.TEXTNOW_COOKIES}} # 多账号cookies_str1|+|cookies_str2
          BARK_URL: ${{secrets.BARK_URL}}
        run: |
          mkdir .cache
          if [ -e ~/cache.tgz ]; then tar -zxf ~/cache.tgz; fi  # 如果当前目录下有 cache.tgz 压缩文件，则进行解压
          sudo apt-get update
          sudo apt-get install xvfb
          xvfb-run --server-args="-screen 0 1024x768x24" node do.js
          tar -zcf ~/cache.tgz .cache # 把.cache 目录压缩成 cache.tgz 文件
